@startuml
'https://plantuml.com/sequence-diagram


!theme cerulean
skinparam backgroundColor #EEF2F7
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor #2471A3
skinparam titleFontColor #2471A3
skinparam sequenceArrowThickness 2
skinparam defaultTextAlignment center
skinparam sequenceParticipantBorderThickness 2
skinparam sequenceParticipantFontColor white
skinparam sequenceLifeLineBorderColor #2471A3
skinparam sequenceLifeLineBorderThickness 1.5
skinparam sequenceParticipantBackgroundColor #2471A3
skinparam sequenceParticipantBorderColor #2471A3
skinparam ArrowColor #2471A3
skinparam ArrowThickness 2

skinparam sequenceLifeLineBackgroundColor #D0D3D4

TITLE "Get maximum temperature difference"
actor RoomOwner

RoomOwner -> System: I want the maximum temperature difference.
System --> RoomOwner: DeviceIdIndoor and TimePeriod?
RoomOwner -> System: DeviceIdIndoor and TimePeriod!
System --> RoomOwner: Present List of devicesIdOutdoor.
RoomOwner -> System: Selected DeviceIdOudoor.
System --> RoomOwner: Maximum temperature difference in deviceIdIndoor and deviceIdOutdoor.

@enduml