create table device
(
    id            bigint        not null
        primary key,
    device_model  varchar(255)  null,
    device_name   varchar(255)  null,
    device_status bit           not null,
    room_id       bigint        not null,
    version       int default 0 not null
);

INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (1, 'Power Meter', 'Power Device', true, 13, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (2, 'Temperature', 'Thermostat', false, 2, 1);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (3, 'Binary Switch', 'Switch', false, 1, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (4, 'Scale', 'Scale ', true, 2, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (5, 'Dew Point ', 'Dew Point', true, 2, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (6, 'Wind', 'Wind Direction', true, 2, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (7, 'Solar Irradiance', 'Solar Irradiance', true, 7, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (8, 'Electric Consuption', 'Electric Consuption', true, 3, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (9, 'Temperature', 'Fridge', true, 3, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (10, 'Temperature', 'Oven', true, 3, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (11, 'Temperature', 'Fryer', true, 3, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (12, 'Temperature', 'Fridge', true, 4, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (13, 'Temperature', 'Oven', true, 4, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (14, 'Temperature', 'Fryer', true, 4, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (15, 'Binary Switch', 'Televison', true, 5, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (16, 'Temperature', 'Home Radiator', true, 5, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (17, 'Binary Switch', 'Roomba', true, 6, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (18, 'Binary Switch', 'Vacuum Cleaner', true, 6, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (19, 'Binary Switch', 'Televison', true, 6, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (20, 'Binary Switch', 'Lamp', true, 8, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (21, 'Binary Switch', 'Television', true, 8, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (22, 'Blind Roller', 'Blind Roller', true, 8, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (23, 'Tempeture', 'Thermostat', true, 7, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (24, 'Dew Point', 'Dew Point', true, 7, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (25, 'Wind Direction', 'Wind Direction', true, 7, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (26, 'Blind Roller', 'Blind Roller', true, 9, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (27, 'Binary Switch', 'Lamp', true, 9, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (28, 'Binary Switch', 'Apple Laptop', true, 10, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (29, 'Binary Switch', 'Printer', true, 10, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (30, 'Binary Switch', 'Laptop Screen ', true, 10, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (31, 'Binary Switch', 'Bathtub', true, 11, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (32, 'Binary Switch', 'Toilet', true, 11, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (33, 'Binary Switch', 'Lamp', true, 12, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (34, 'Temperature', 'Thermostat', true, 12, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (35, 'Binary Switch', 'Lamp', true, 13, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (36, 'Binary Switch', 'Radio', true, 13, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (37, 'Binary Switch', 'Bathtub', true, 14, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (38, 'Binary Switch', 'Toilet', true, 14, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (39, 'Humidity', 'Humidity', true, 1, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (40, 'Binary Switch', 'Microwave', true, 3, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (41, 'Binary Switch', 'Lamp', false, 14, 1);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (42, 'Wind Direction', 'Wind Direction', true, 15, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (43, 'Binary Switch', 'Dj Board', true, 16, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (44, 'Binary Switch', 'Lamp', true, 17, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (45, 'Binary Switch', 'Apple Laptop', true, 18, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (46, 'Blind Roller', 'Blind Roller', true, 17, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (47, 'Power Meter', 'Power Device', true, 26, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (48, 'Tempeture', 'Thermostat', true, 26, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (49, 'Binary Switch', 'Switch', true, 26, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (50, 'Scale', 'Scale ', true, 26, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (51, 'Dew Point ', 'Dew Point', true, 20, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (52, 'Wind', 'Wind Direction', true, 20, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (53, 'Solar Irradiance', 'Solar Irradiance', true, 20, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (54, 'Electric Consuption', 'Electric Consuption Device', true, 26, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (55, 'Binary Switch', 'Fridge', true, 21, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (56, 'Binary Switch', 'Oven', true, 21, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (57, 'Binary Switch', 'Fryer', true, 21, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (58, 'Binary Switch', 'Televison', true, 24, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (59, 'Tempeture', 'Home Radiator', true, 24, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (60, 'Binary Switch', 'Roomba', true, 19, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (61, 'Binary Switch', 'Vacuum Cleaner', true, 19, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (62, 'Binary Switch', 'Televison', true, 19, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (63, 'Binary Switch', 'Lamp', true, 22, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (64, 'Binary Switch', 'Television', true, 22, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (65, 'Blind Roller', 'Blind Roller', true, 22, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (66, 'Tempeture', 'Thermostat', true, 28, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (67, 'Dew Point', 'Dew Point', true, 28, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (68, 'Wind Direction', 'Wind Direction', true, 28, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (69, 'Blind Roller', 'Blind Roller', true, 23, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (70, 'Binary Switch', 'Lamp', true, 23, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (71, 'Binary Switch', 'Apple Laptop', true, 25, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (72, 'Binary Switch', 'Printer', true, 25, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (73, 'Binary Switch', 'Laptop Screen ', true, 25, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (74, 'Binary Switch', 'Bathtub', true, 27, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (75, 'Binary Switch', 'Toilet', true, 27, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (76, 'Binary Switch', 'Lamp', true, 27, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (77, 'Temperature', 'Thermostat', true, 27, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (78, 'Binary Switch', 'Lamp', true, 28, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (79, 'Binary Switch', 'Radio', true, 28, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (80, 'Binary Switch', 'Lamp', true, 24, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (81, 'Wind Direction', 'Wind Direction', true, 28, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (82, 'Binary Switch', 'Lamp', true, 24, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (83, 'Binary Switch', 'Apple Laptop', true, 24, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (84, 'Blind Roller', 'Blind Roller', true, 24, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (85, 'Power Meter', 'Power Device', true, 33, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (86, 'Tempeture', 'Thermostat', true, 33, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (87, 'Binary Switch', 'Switch', true, 33, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (88, 'Scale', 'Scale ', true, 33, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (89, 'Dew Point ', 'Dew Point', true, 38, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (90, 'Wind', 'Wind Direction', true, 38, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (91, 'Solar Irradiance', 'Solar Irradiance', true, 38, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (92, 'Electric Consuption', 'Electric Consuption Device', true, 33, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (93, 'Binary Switch', 'Fridge', true, 35, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (94, 'Binary Switch', 'Oven', true, 35, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (95, 'Binary Switch', 'Fryer', true, 35, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (96, 'Binary Switch', 'Televison', true, 29, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (97, 'Tempeture', 'Home Radiator', true, 29, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (98, 'Binary Switch', 'Roomba', true, 29, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (99, 'Binary Switch', 'Vacuum Cleaner', true, 37, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (100, 'Binary Switch', 'Televison', true, 37, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (101, 'Binary Switch', 'Lamp', true, 37, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (102, 'Binary Switch', 'Television', true, 30, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (103, 'Blind Roller', 'Blind Roller', true, 30, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (104, 'Tempeture', 'Thermostat', true, 30, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (105, 'Dew Point', 'Dew Point', true, 30, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (106, 'Blind Roller', 'Blind Roller', true, 31, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (107, 'Binary Switch', 'Lamp', true, 31, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (108, 'Binary Switch', 'Apple Laptop', true, 32, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (109, 'Binary Switch', 'Printer', true, 32, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (110, 'Binary Switch', 'Laptop Screen ', true, 32, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (111, 'Binary Switch', 'Bathtub', true, 36, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (112, 'Binary Switch', 'Toilet', true, 36, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (113, 'Binary Switch', 'Lamp', true, 36, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (114, 'Temperature', 'Thermostat', true, 36, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (115, 'Binary Switch', 'Lamp', true, 34, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (116, 'Binary Switch', 'Radio', true, 34, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (117, 'Binary Switch', 'Lamp', true, 34, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (118, 'Wind Direction', 'Wind Direction', true, 34, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (119, 'Binary Switch', 'Lamp', true, 37, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (120, 'Binary Switch', 'Apple Laptop', true, 37, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (121, 'Blind Roller', 'Blind Roller', true, 29, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (202, 'Oi', 'Firdge', true, 10, 0);
INSERT INTO smarthome.device (id, device_model, device_name, device_status, room_id, version) VALUES (252, 'Xiaomi', 'Fryer', true, 1, 0);
