create table sensor
(
    sensor_id      bigint        not null
        primary key,
    device_id      bigint        not null,
    sensor_model   varchar(255)  null,
    sensor_name    varchar(255)  null,
    sensor_type_id varchar(255)  null,
    version        int default 0 not null
);

INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (1, 1, 'InstantPowerConsumptionSensor', 'Instant Power', 'InstantPowerConsumptionSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (2, 1, 'TemperatureSensor', 'Thermostat', 'TemperatureSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (3, 2, 'TemperatureSensor', 'Thermostat', 'TemperatureSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (4, 1, 'InstantPowerConsumptionSensor', 'House Power Meter', 'InstantPowerConsumptionSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (5, 4, 'ScaleSensor', 'Scale Sensor', 'ScaleSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (6, 3, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (7, 4, 'ScaleSensor', 'Scale Sensor', 'ScaleSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (8, 5, 'DewPointSensor', 'Dew Point', 'DewPointSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (9, 6, 'WindSensor', 'Wind Direction', 'WindDirection', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (10, 7, 'SolarIrradianceSensor', 'Solar Irradiance', 'SolarIrradianceSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (11, 8, 'ElectricEnergyConsumptionSensor', 'Electric Energy', 'ElectricEnergyConsumptionSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (12, 9, 'TemperatureSensor', 'Thermostat', 'TemperatureSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (13, 10, 'TemperatureSensor', 'Thermostat', 'TemperatureSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (14, 11, 'TemperatureSensor', 'Thermostat', 'TemperatureSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (15, 12, 'TemperatureSensor', 'Thermostat', 'TemperatureSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (16, 13, 'TemperatureSensor', 'Thermostat', 'TemperatureSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (17, 14, 'TemperatureSensor', 'Thermostat', 'TemperatureSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (18, 15, 'BinarySensor', 'Television Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (19, 16, 'TemperatureSensor', 'Thermostat', 'TemperatureSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (20, 17, 'BinarySensor', 'Roomba', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (21, 18, 'BinarySensor', 'Vaccum Cleaner', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (22, 19, 'BinarySensor', 'Television Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (23, 20, 'BinarySensor', 'Lamp Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (24, 21, 'BinarySensor', 'Television Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (25, 22, 'ScaleSensor', 'Blind Roller ', 'ScaleSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (26, 23, 'TemperatureSensor', 'Thermostat', 'TemperatureSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (27, 24, 'DewPointSensor', 'Dew Point', 'DewPointSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (28, 25, 'WindSensor', 'Wind Direction', 'WindSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (29, 26, 'ScaleSensor', 'Blind Roller', 'ScaleSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (30, 27, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (31, 28, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (32, 29, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (33, 30, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (34, 31, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (35, 32, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (36, 33, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (37, 34, 'TemperatureSensor', 'Thermostat', 'TemperatureSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (38, 35, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (39, 36, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (40, 37, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (41, 38, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (42, 39, 'HumiditySensor', 'Humidity', 'HumiditySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (43, 40, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (44, 41, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (45, 42, 'WindSensor', 'Wind Direction', 'WindSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (46, 43, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (47, 44, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (48, 45, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (49, 46, 'ScaleSensor', 'Blind Roller', 'ScaleSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (50, 47, 'InstantPowerConsumptionSensor', 'House Power Meter', 'InstantPowerConsumptionSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (51, 48, 'TemperatureSensor', 'Thermostat', 'TemperatureSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (52, 49, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (53, 50, 'ScaleSensor', 'Scale', 'ScaleSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (54, 51, 'DewPointSensor', 'Dew Point', 'DewPointSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (55, 52, 'WindSensor', 'Wind Direction', 'WindSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (56, 53, 'SolarIrradianceSensor', 'Solar Irradiance', 'SolarIrradianceSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (57, 54, 'ElectricEnergyConsumputionSensor', 'Electric Consuption', 'ElectricEnergyConsumputionSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (58, 55, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (59, 56, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (60, 57, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (61, 58, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (62, 59, 'TemperatureSensor', 'Thermostat', 'TemperatureSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (63, 60, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (64, 61, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (65, 62, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (66, 63, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (67, 64, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (68, 65, 'ScaleSensor', 'Blind Roller', 'ScaleSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (69, 66, 'TemperatureSensor', 'Thermostat', 'TemperatureSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (70, 67, 'DewPointSensor', 'Dew Point', 'DewPointSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (71, 68, 'WindSensor', 'Wind Direction', 'WindSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (72, 69, 'ScaleSensor', 'Blind Roller', 'ScaleSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (73, 70, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (74, 71, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (75, 72, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (76, 73, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (77, 74, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (78, 75, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (79, 76, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (80, 77, 'TemperatureSensor', 'Thermostat', 'TemperatureSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (81, 78, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (82, 79, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (83, 80, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (84, 81, 'WindSensor', 'Wind Direction', 'WindSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (85, 82, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (86, 83, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (87, 84, 'ScaleSensor', 'Blind Roller', 'ScaleSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (89, 85, 'InstantPowerConsumptionSensor', 'House Power Meter', 'InstantPowerConsumptionSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (90, 86, 'TemperatureSensor', 'Thermostat', 'TemperatureSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (91, 87, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (92, 88, 'ScaleSensor', 'Blind Roller', 'ScaleSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (93, 89, 'DewPointSensor', 'Dew Point', 'DewPointSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (94, 90, 'WindSensor', 'Wind Direction', 'WindSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (95, 91, 'SolarIrradianceSensor', 'Solar Irradiance', 'SolarIrradianceSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (96, 92, 'ElectricEnergyConsumputionSensor', 'Electric Energy', 'ElectricEnergyConsumputionSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (97, 93, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (98, 94, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (99, 95, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (100, 96, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (101, 97, 'TemperatureSensor', 'Thermostat', 'TemperatureSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (102, 98, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (103, 99, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (104, 100, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (105, 101, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (106, 102, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (107, 103, 'ScaleSensor', 'Blind Roller', 'ScaleSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (108, 104, 'TemperatureSensor', 'Thermostat', 'TemperatureSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (109, 105, 'DewPointSensor', 'Dew Point', 'DewPointSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (110, 106, 'ScaleSensor', 'Blind Roller', 'ScaleSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (111, 107, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (112, 108, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (113, 109, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (114, 110, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (115, 111, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (116, 112, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (117, 113, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (118, 114, 'TemperatureSensor', 'Thermostat', 'TemperatureSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (119, 115, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (120, 116, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (121, 117, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (122, 118, 'WindSensor', 'Wind Direction', 'WindSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (123, 119, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (124, 120, 'BinarySensor', 'Switch', 'BinarySensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (125, 121, 'ScaleSensor', 'Blind Roller', 'ScaleSensor', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (152, 30, 'InstantPowerConsumptionSensor', 'Battery', 'Battery', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (202, 30, 'TemperatureSensor', 'Humidity', 'Thermal', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (203, 202, 'TemperatureSensor', 'Temp', 'Themp', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (252, 39, 'TemperatureSensor', 'BlindRoller', 'cd', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (302, 39, 'TemperatureSensor', 'Temperature sensor', 'Thermometer', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (303, 252, 'TemperatureSensor', 'Temperature Air Fryer', 'Cooking', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (304, 39, 'ScaleSensor', 'BlindRoller', 'vsd', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (305, 252, 'TemperatureSensor', 'Heat Detector', 'Grill', 0);
INSERT INTO smarthome.sensor (sensor_id, device_id, sensor_model, sensor_name, sensor_type_id, version) VALUES (306, 22, 'ScaleSensor', 'Scale', 'Scale', 0);
